version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: electron
    versions:
    - ">= 7.a"
    - "< 8"
  - dependency-name: electron
    versions:
    - ">= 9.a"
    - "< 10"
  - dependency-name: electron-winstaller
    versions:
    - ">= 3.a"
    - "< 4"
  - dependency-name: "@types/electron-winstaller"
    versions:
    - ">= 4.a"
    - "< 5"
  - dependency-name: "@types/node"
    versions:
    - ">= 11.a"
    - "< 12"
  - dependency-name: "@types/node"
    versions:
    - ">= 12.a"
    - "< 13"
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a"
    - "< 14"
  - dependency-name: "@types/node"
    versions:
    - ">= 14.a"
    - "< 15"
