language: node_js

node_js:
- '10'

# http://docs.travis-ci.com/user/build-lifecycle/
before_install:
  - curl https://yarnpkg.com/install.sh -sSfL | bash -s --
  - export PATH="${HOME}/.yarn/bin:${PATH}"

before_script:
  - yarn boot

script:
  - yarn test

notifications:
  email: false
