language: node_js

node_js:
  - '11'

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      before_script:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

git:
  submodules: false

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - node_modules
    - electron/node_modules

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - yarn boot

script:
  - yarn test

notifications:
  email: false
